// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIlqtKo52M2nQPKQ2jYbCr2QkGC9Z_PYk',
    appId: '1:377833765288:web:78453d1a782d7ee71a859d',
    messagingSenderId: '377833765288',
    projectId: 'emialauthentication',
    authDomain: 'emialauthentication.firebaseapp.com',
    storageBucket: 'emialauthentication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGo6xF3n3VxGipcMjezp4JyqSW9XTEWps',
    appId: '1:377833765288:android:4991588d5ba8d7831a859d',
    messagingSenderId: '377833765288',
    projectId: 'emialauthentication',
    storageBucket: 'emialauthentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBdmbGQkmiGRqePQSsmQAvhY_vZeX-40',
    appId: '1:377833765288:ios:a46dd1ae5d23f6541a859d',
    messagingSenderId: '377833765288',
    projectId: 'emialauthentication',
    storageBucket: 'emialauthentication.appspot.com',
    iosClientId: '377833765288-do1snddq2q9a0qmr1c6mso3dt6fo0h2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCBdmbGQkmiGRqePQSsmQAvhY_vZeX-40',
    appId: '1:377833765288:ios:a46dd1ae5d23f6541a859d',
    messagingSenderId: '377833765288',
    projectId: 'emialauthentication',
    storageBucket: 'emialauthentication.appspot.com',
    iosClientId: '377833765288-do1snddq2q9a0qmr1c6mso3dt6fo0h2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
